config/routes.rb
MeetingSpot::Application.routes.draw do

  root :to => 'maps#home'

  resources :maps do
    resources :addresses
    post '/places' => 'places#create'
    get '/places/:id' => 'places#show'
    get '/places' => 'places#selection'
    put '/places/:id' => 'places#update'
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :place, :name
  validates :place, :presence => true
  belongs_to :map
  belongs_to :user
  geocoded_by :place   # can also be an IP address
  after_validation :geocode,  if: ->(obj){ obj.place.present? and obj.place_changed? } # auto-fetch coordinates
end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessor :city
  attr_accessible :name, :middle_ground_lat, :middle_ground_long, :city
  has_many :addresses
  has_many :users, :through => :addresses
  has_many :map_places
  has_many :places, :through => :map_places
  accepts_nested_attributes_for :addresses

  def coords(city)
    if city == ""
      city = "New York, NY" #default to NY
    end
    coords = Geocoder.coordinates(city)
    self.middle_ground_lat = coords[0]
    self.middle_ground_long = coords[1]
  end

  def map_title
    self.name == nil || self.name.length == 0  ? "Your Map" : self.name
  end

  def addresses_to_json
    a = self.addresses
    a.to_json(:only => [:latitude, :longitude])
  end

  def address_array
    addy_array = []
    self.addresses.each do |address|
      addy_array << [address.latitude, address.longitude]
    end
    addy_array
  end

end

app/models/map_place.rb
class MapPlace < ActiveRecord::Base
  belongs_to :map
  belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :name, :latitude, :longitude, :price_level, :rating, :reference, :types
  has_many :map_places
  has_many :maps, :through => :map_places

  def self.save_json(places_data, map_id)
    places_data.each do |index, place|
      if Place.find_by_latitude(place["latitude"]).nil? && Place.find_by_longitude(place["longitude"]).nil?
        @place = Place.new(place)
        @place.save
        if index.to_i < 5
          @map = Map.find(map_id) 
          @map.places << @place
        end
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :addresses
  has_many :maps, :through => :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  
  def index
    @addresses = Address.all
  end

  def new
    @map = Map.find(params[:id])
    # @address = Address.
    # @map.add
  end

  def create
    @map = Map.find(params[:map_id])
    @address = Address.create(params[:map][:addresses_attributes]["0"])
    @map.addresses << @address
    # @address = Address.new(params[:address])
    # @map = params[:id]
     # if @address.save 
    #   # redirect_to map_address_path
     redirect_to "/maps/#{@map.id}"
      # redirect_to "/maps/#{@map}/addresses/#{@address.id}"
    # else
    #   render new
     # end
  end

  def show
    @address = Address.find(params[:id])
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update_attributes(params[:address])
      redirect_to @address
    else
      render 'edit'
    end
  end

  def destroy
    @address = Address.find(params[:id]).delete
    @map = Map.find(params[:map_id])
    redirect_to @map
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def home
    @body_class = "home_container"
    @map = Map.new
  end

  def index
    @maps = Map.all
  end

  def show
    @map = Map.find(params[:id])
  end

  def new
    @map = Map.new
  end

  def create
    @map = Map.new(params[:map])
    @map.coords(params[:map][:city])

    if @map.save
      redirect_to @map
    else
      render new
    end
  end

  def edit
    @map = Map.find(params[:id])
  end

  def update
    @map = Map.find(params[:id])
    @map.coords(params[:map][:city])

    if @map.update_attributes(params[:map])
      redirect_to @map
    else
      render 'edit'
    end
  end

  def destroy
    @map = Map.delete(params[:id])
    redirect_to maps_path
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def create
    respond_to do |format|
      format.json { Place.save_json(params["places"], params["map_id"]) }
    end
    redirect_to '/maps/'+params["map_id"]
  end

  def show
  end

  def selection
    @map = Map.find(params["map_id"])
    @places = @map.places
    respond_to do |format|
      format.js {render :json => @places}
    end
  end

  def update
  end
  
end

app/controllers/users_controller.rb
class UserController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def update  
  end

  def edit
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<%= form_for "address", :url => "/maps/#{params[:map_id]}/addresses" do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation"> 
      <h2> <%= pluralize(@address.errors.count, "error") %> </h2> 
      <ul>
        <% @address.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>
    <%= f.label :place, 'Address' %>
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/index.html.erb
<%= render "form" %>

app/views/addresses/new.html.erb
<%= render "form" %>

app/views/addresses/show.html.erb
<h1><%= @address.name.titleize %>

<script>
function initialize(){
    var mapProp = {
        center:new google.maps.LatLng(<%= @address.latitude %>, <%= @address.longitude %>),
        zoom:12,
        mapTypeId:google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
    var marker = new google.maps.Marker({
        position:mapProp.center,
    });
    marker.setMap(map);
}

// var myCenter=new google.maps.LatLng(<%= @address.latitude %>, <%= @address.longitude %>);

google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div id="googleMap" style="width:60%;height:380px;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meeting Spot</title>
    <link rel="stylesheet" href="/stylesheets/custom.css">
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag '/assets/favicon.png' %>
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <script src="http://maps.googleapis.com/maps/api/js?key=<%= ENV["KEEFS_API_KEY"] %>&libraries=places&sensor=false"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  </head>
  <body class="<%= @body_class %>">
    <h1 id="main">Let us help you figure out where to meet!</h1>
    <%= yield %>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="/assets/jQuery.blockUI.js"></script>

  </body>
</html>

app/views/maps/_address_form.html.erb
<%= form_for @map, :url => "/maps/#{params[:id]}/addresses", :method => "post" do |f| %>
  <%= f.fields_for :addresses, @map.addresses.build do |ff| %>
    <div>
      <%= ff.label :name %>
      <%= ff.text_field :name %>
      <%= ff.label :place, "Location:" %>
      <%= ff.text_field :place %>
      <%= ff.submit %>
    </div>
  <% end %>
<% end %>

app/views/maps/_form.html.erb
<%= form_for @map do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation"> 
      <h2> <%= pluralize(@map.errors.count, "error") %> </h2> 
      <ul>
        <% @map.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city, 'What city are you meeting in?' %>
    <%= f.text_field :city %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Edit <%= @map.map_title.titleize %> Map</h1>

<%= render "form" %>
<br>
<%= link_to "Back to all maps", maps_path %>

app/views/maps/edit.html.haml
<h1>EDIT!!!!</h1>

app/views/maps/home.html.erb
<div class="home_content">
  <p>You just need to tell us your city, and where you and your friends are coming from.
    <br>Let us handle the rest.</p>
    <p>We'll find you a central meeting place by public transit travel time,
    <br>that fits your city and your life.</p>

    <%= form_for @map do |f| %>
      <% if @map.errors.any? %>
        <div id="error_explanation">
          <h2> <%= pluralize(@map.errors.count, "error") %> </h2>
          <ul>
            <% @map.errors.full_messages.each do |message| %>
            <li> <%= message %> </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :name, 'Just give your map a name' %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :city, 'And tell us what city you\'re in!' %><br>
        <%= f.text_field :city %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit 'Get Started!'%>
      </div>
    <% end %>
    
</div>

app/views/maps/index.html.erb
<h1>Your Maps</h1>
<table>
  <tr>
    <th class="top">Map Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @maps.each do |map| %>
    <tr class="maplist">
      <td><%= map.name %></td>
      <td></td>
      <td><%= link_to 'Show', map %></td>
      <td><%= link_to 'Edit', edit_map_path(map) %></td>
      <td><%= link_to 'Delete', map, {:method => 'delete', :data => {:confirm => 'Are you sure you want to delete? You\'ll be destroying a world :('}} %></td>
    </tr>
  <% end %>

</table>

<br>

<%= link_to 'Create a new map', new_map_path %>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render "form" %>

<br>

<%= link_to "Back to all maps", maps_path %>

app/views/maps/show.html.erb
<div class="title-bar">
  <h2><%= @map.map_title %></h1>
</div>

<script>
    var lat = <%=  @map.middle_ground_lat %>;
    var lon = <%= @map.middle_ground_long %>;
    var bounds = new google.maps.LatLngBounds();
    var addressArray = convertToLatLonObjects(<%= @map.address_array %>);
    var markers = <%= raw @map.addresses_to_json %>;
    var map_id = <%= @map.id %>;
    var selectionPlaces  = <%= raw @map.places.to_json %>;
</script>

<div id="wrapper">
  <div id="googleMap" class="centered"></div>
  <div id="googlePlaces" class="hidden"><ul></ul></div>
</div>
<div class="address-form">
  <%= render "address_form" %>
</div>
<br>
<div class="address_list">
  <img src="/img/house.png">
  <ul>
    <% if @map.addresses.length > 1 %>
      <li class="title">Your Addresses:</li>
    <% else %>
      <li class="title">No Addresses Yet!</li>
    <% end %>
    <% @map.addresses.each do |address| %>
      <% next if address.id.nil? %>
      <li><%= address.name.capitalize %>: <%= address.place.titleize %>&nbsp;&nbsp;<%= link_to "delete", map_address_path(address.map_id, address.id), :confirm => "Are you sure you want to delete this address?", :method => :delete %></li>
    <% end %>
  </ul>
  <img src="/img/desk.png">
</div>
<div class="userInput">
  <form class="placeParams">
    <fieldset>
      <legend class="venue">Venue</legend>
      <p>
        <input type="checkbox" name="placeType" id="pT_1" value="bar" checked />
        <label for="pT_1">Bar</label>
      </p>
      <p>
        <input type="checkbox" name="placeType" id="pT_2" value="cafe" checked/>
        <label for="pT_2">Cafe</label>
      </p>
      <p>
        <input type="checkbox" name="placeType" id="pT_3" value="restaurant" checked/>
        <label for="pT_3">Restaurant</label>
      </p>
    </fieldset>
  </form>

  <form class="placeParams">
    <fieldset>
      <legend class="time">Time and Date</legend>
      <p>
        <input type="datetime-local" name="placeDate" id="placeDate-id" step="1"/>
      </p>
    </fieldset>
  </form>

  <form class="placeParams">
    <fieldset>
      <legend class="cost">Maximum Price</legend>
      <p>
        <input type="radio" name="placePrice" id="price_1" value="1" />
        <label for="pT_1">$</label>
      </p>
      <p>
        <input type="radio" name="placePrice" id="price_1" value="2" />
        <label for="pT_1">$$</label>
      </p>
      <p>
        <input type="radio" name="placePrice" id="price_2" value="3" />
        <label for="pT_2">$$$</label>
      </p>
      <p>
        <input type="radio" name="placePrice" id="price_3" value="4" checked />
        <label for="pT_3">$$$$</label>
      </p>
    </fieldset>
  </form>

  <button id="place-btn">Find Meeting Place</button>
</div>

<br>
<br>
<!-- <%= link_to "Back to all maps", maps_path %> -->

<script>
  //Set Default value of Date/Time based on local time
Date.prototype.toDateInputValue = (function() {
    var local = new Date(this);
    local.setMinutes(this.getMinutes() - this.getTimezoneOffset()); // accounts for timezone differences
    return local.toJSON();
});

var d = new Date();
$('#placeDate-id').val(d.toDateInputValue().slice(0,-1));

google.maps.event.addDomListener(window, "load", initialize);
google.maps.event.addDomListener(window, "load", addAllMarkers);

$(document).ready(function() {
    $('#place-btn').click(function() {
        $.blockUI({ message: "<div class='loader8'></div>",css: {
            border: 'none',
            padding: '15px',
            backgroundColor: '#000',
            '-webkit-border-radius': '10px',
            '-moz-border-radius': '10px',
            opacity: .5,
            color: '#fff'
        } });
        // setTimeout($.unblockUI, 2000);
    });
});
</script>